version: '3'

services:      
  web:
    build:
      dockerfile: Dockerfile
      context: src/.
    environment:
      - BotSettings__ApiToken=${BOT_TOKEN}
      - DataBaseSettings__ConnectionString=${BOT_DB_CONNECTION_STRING}
      - JobSchedulerSettings__ConnectionString=${JOB_SCHEDULER_DB_CONNECTION_STRING}
    ports:
      - 5001:5001
