version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - /tmp/pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  scheduler:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_SCHEDULER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEDULER_PASSWORD}
    volumes:
        - /tmp/pgdata_scheduler:/var/lib/postgresql/data:rw
    ports:
      - 5431:5432
      
  web:
    build:
      dockerfile: Dockerfile
      context: src/.
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=${USER_SECRETS_ID}
    volumes:
      - $HOME/.microsoft/usersecrets/${USER_SECRETS_ID}:/root/.microsoft/usersecrets/${USER_SECRETS_ID}
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - scheduler
